name: fake_hisepy
channels:
  - conda-forge
  - defaults
  - ejohnsms
dependencies:
  - python=3.11
  - conda-build
  - conda-verify
  - grayskull
  - numpy
  - pandas
  - termcolor
  - h5py
  - pyreadr
  - plotly
  - tomli
  - pip
  - pip:
    - build
    - twine
    - setuptools
