# help with interacting with materialized view for emr/subject/file etc
# can this just be a list of values...?

[MATERIALIZED_VIEW]
QUERYABLE_FIELDS = ["file", "sample", "subject"]
EMR = "emr"
LAB = "lab"

[FILETYPES]
SCRNA_RESULT = "scRNA-seq-labeled"
DASH_APP = "dash_app.tar.gz"

[PROMPTS]
UPLOAD = "You are trying to upload file IDs."
ABSTRACTION = "You are about to save an abstract visualization template."

# Authorization config

[AUTHORIZE]
METADATA_SERVER_ROOT = "http://metadata.google.internal/computeMetadata/v1/instance"
INSTANCE_NAME_PATH = "name"
CLIENT_ID_PATH = "attributes/iap-client-id"
ACCOUNT_GUID_PATH = "attributes/currentAccountGuid"
IDENTITY_PATH = "service-accounts/default/identity"
SERVER_ID_PATH = "attributes/hise-server"
TOKEN_ENV = "TOKEN_GENERATOR"

[PROJECT_STORE]
TAG_FIELD_NAME = "availability"
PROJECT_STORE_ENDPOINT = "analysis/projectStore"
AVAILABLE_TAG = "available"
DELETED_TAG = "marked_for_deletion"
PROMOTION_TAG = "marked_for_promotion"

[PROJECT_FOLDER]
PROJECT_FOLDER_ENDPOINT = "analysis/projectFolder"

# hydration endpoints

[HYDRATION]
HYDRATION_NAME = "hydration"
USER_FOLDER_PATH = "hydration/analysis/userFolder"
FILE_SEARCH_PATH = "hydration/analysis/files"
DESCRIPTORS_PATH = "hydration/analysis/descriptors"
DOWNLOAD_PATH = "hydration/source/server"
UPLOAD_PATH = "hydration/source/studyspace/file"
QUERY_SEARCH_PATH = "hydration/analysis/query"
WEBSOCKET_PATH = "hydration/source/stream/open"
HISE_WIDE_STATIC_IMG_PATH = "hydration/source/abstraction/save"

[AMDS]
AMDS_NAME = "accountmanager"
PROJECT_PATH = "accountmanager/project"

# ledger endpoints

[LEDGER]
LEDGER_NAME = "ledger"
SAMPLE_SEARCH_PATH = "ledger/sample/q"
SUBJECT_SEARCH_PATH = "ledger/subject/q"
FILE_SEARCH_PATH = "ledger/file/q"
RESULT_FILE_SEARCH_PATH = "ledger/resultfile"

# tracer endpoints

[TRACER]
TRACER_NAME = "tracer"
TRACE_PATH = "tracer/trace"
STUDY_SPACE_PATH = "tracer/studyspace"
FILE_SET = "tracer/fileset"

# globals specific for IDE

[IDE]
CACHE_DIR = "cache"
HOME_DIR = "/home/jupyter"
CACHE_LOG_NAME = ".hisefilelog.rds"
DOWNLOAD_CHUNK_SIZE = 102400

# NOTE: should this be separate from the rest of scheduler section?

[TOOLCHAIN]
SCHEDULER_PATH = "toolchain/scheduler"
VISUALIZATION_PATH = "toolchain/visualization"
ABSTRACTION_PATH = "toolchain/abstraction"
UPLOAD_FILE_PATH = "toolchain/file"
SAVE_DASH_APP_PATH = "toolchain/visualization/dash"
DEPLOY_DASH_APP_PATH = "toolchain/deploy/visualization"
TOOLCHAIN_IDE = "toolchain/instances"
UPLOAD_HARVEST_LOWER_BOUND_MB = 10.0

[ABSTRACTION]
# VIZ_CONFIGS_PATH = "/home/jupyter/examples/Visualization_apps/dash/configs"
VIZ_CONFIGS_PATH = "../src/fake_hisepy/config"

# scheduler endpoints and global...

[SCHEDULER]
PLATFORM_DEFAULT = "Notebook"
PLATFORM_LOUVAIN = "Louvain"
JOB_ID_FIELD = "id"
FILE_IDS_FIELD = "fileIds"
STATUS_FIELD = "status"
TITLE_FIELD = "title"
LEDGER_OUTPUT_FIELD = "ledger_output"
NOTEBOOK_NAME_FIELD = "notebook_name"
INSTANCE_NAME_FIELD = "instance_name"
NOTEBOOK_PATH_FIELD = "notebook_path"
INPUT_FILES_FIELD = "input_files"
OUTPUT_FILES_FIELD = "output_files"
PLATFORM_FIELD = "platform"
PROJECT_FIELD = "project"
JOB_COMPLETE_STATUS = "Completed"
