package:
  name: fake_hisepy
  version: 0.1.0  # Update this version as needed

source:
  path: ../

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - numpy
    - pandas

test:
  imports:
    - fake_hisepy

about:
  home: https://github.com/yourusername/fake_hisepy  # Update the URL
  license: MIT  # Update as appropriate
  summary: 'Description of the fake_hisepy project.'
