{% set name = "fake_hisepy" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: file:///Users/ed.johnson/dev/fake_hisepy/dist/fake_hisepy-0.1.0.tar.gz
  sha256: baefe2fc1781f68222798585b2cb34b989b8dc3cb2598a8fcd4381a8759931c5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=43.0.0
    - wheel
    - pip
  run:
    - python >=3.6
    - numpy
    - pandas

test:
  imports:
    - src
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aifimmunology/fake_hisepy
  summary: Fake placeholder for the HISE Python SDK
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - paulmariz
